name: Check for Version Tag

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest tag
        id: get-tag
        run: |
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Check if latest tag is a version tag
        run: |
          if [[ ! "$LATEST_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: No version tag found. Latest tag is $LATEST_TAG"
            exit 1
          fi
        env:
          LATEST_TAG: ${{ env.LATEST_TAG }}
